spring:
  datasource:
    url: jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=Database
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: 
    username: sa
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
