spring:
  datasource:
    url: jdbc:h2:~/test 
    #jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    password: 
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true